### ISSUE TITLE
HTTP Headers are ignored

### ISSUE THREAD

**Issue by scholzi100** [microbean/microbean-jersey-netty#10]
Headers in ContainerRequest are always size 0. 
Headers are only set using injection, but not in ContainerRequest.

` ContainerRequest#headers(...)` is never called inside `AbstractContainerRequestDecoder` or its derivatives.

**Comment by ljnelson** [comment]
! Will investigate pronto.

**Comment by ljnelson** [comment]
@scholzi100 Thanks for the bug report; can't believe I missed this.  See https://github.com/microbean/microbean-jersey-netty/pull/11 and see what you think

**Comment by ljnelson** [comment]
Fixed; 0.24.1 is making its way to Maven Central.
