### ISSUE TITLE
SimpleContainer is not used

### ISSUE THREAD

**Issue by scholzi100** [microbean/microbean-jersey-netty#15]
Is there a reason why `ApplicationHandler` is used in favour of `SimpleContainer` in constructing a pipeline?

A container could bring support for hot reloading the `resources`.

**Comment by ljnelson** [comment]
That was explicitly something I wanted to avoid.  There may be an opportunity to refactor the two concepts into functional constructs, however, that might permit either to be used.  I'll take a look.

**Comment by ljnelson** [comment]
See #16.
